### PR TITLE
WIP: ESO refactor

### PR DESCRIPTION
**Pull request by keflavich**
@bsipocz I'm building on whatever changes you made to make the eso query forms work again.

The new forms are similar to the old, but with subtle changes that I haven't
fully resolved yet; it looks like my query parameters are _nearly_ but not
_exactly_ identical to what is submitted using the browser now.

The help form works, but is ugly.

### CODE REVIEW

**Comment by keflavich** [comment]
I'm presently stuck at this error:

```
b'# SIMBAD coordinates for w51 :  19 23 42.0, +14 30 33.0.\n#\n# DB ERROR: The database server reported an error: [, Error in dbsqlexec.]\n#'
```

**Comment by bsipocz** [comment]
I'm sorry that this hasn't been finished aleady. I'm visiting family atm
with little internet connection, so couldn't work much on astoquery either.
Anyway I'll back tomorrow and will review this asap.

**Comment by bsipocz** [comment]
@keflavich - I'm thinking about merging this now, and work on a bit on the outstanding issues, unless it clashes with you working on it, too.

**Comment by keflavich** [comment]
:+1: go ahead, I'm not working on this today

**Pull request merged**
